### ISSUE TITLE
Need to unpublish bitlang.cobol and cobol-themes

### ISSUE THREAD

**Issue by spgennard** [eclipse/open-vsx.org#213]
Sorry to bother you but can you please unpublish my two extensions bitlang.cobol and bitlang.cobol-themes as I need to address some issues with the extensions.

with thanks in advance

**Comment by spoenemann** [comment]
Would you like to delete all currently published versions? Note that this would have consequences: losing stats like download count, users won't find the extension anymore.

Would it be feasible for you to address the issues, publish a new version, and then we delete the previous versions?

**Comment by spgennard** [comment]
Yes, unfortunately I need to remove the previous versions and I understand the consequences

**Comment by spoenemann** [comment]
I deleted all versions of the two extensions.

@spgennard if by any means possible, please disclose the reasons for this request and the upcoming changes. A good place to document this would be the CHANGELOG and/or README files of your extensions.

@zimlu02 I had to delete the older version of `BroadcomMFD/code4z-extension-pack` because it included `bitlang.cobol`. Unfortunately a new bug (https://github.com/eclipse/openvsx/issues/202) led to the later version of the extension pack being deleted, too. I'm sorry for the inconvenience. Would you mind republishing the current version?

**Comment by zimlu02** [comment]
@spoenemann sure, no problem. Thanks for letting me know.

**Comment by spgennard** [comment]
@spoenemann  & @zimlu02  - thanks for you help, time to close the issue
